name = "sbd"
description = "A one page HTML theme for Sleeping Bear Design."
homepage = "//github.com/bhberson/sleeping-bear-design"
tags = ["creative", "portfolio"]
features = ["responsive", "portfolio"]
min_version = 0.14

[author]
  name = "Brody Berson"
  homepage = "//brodyberson.com/"

# If porting an existing theme
[original]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"
  repo = "//github.com/digitalcraftsman/hugo-creative-theme"
